# Makefile for connectivity homework
# @author Fuat Keceli
# @revision $revision$
# @ID $Id: Makefile 8267 2009-04-24 05:17:51Z keceli $
#
#===========================================================================
#

MAKE_FILE ?= /opt/xmt/class/make/connectivity.mk

include $(MAKE_FILE)
